//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeeperPRO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        public int ID_Application { get; set; }
        public int ID_Visitors { get; set; }
        public Nullable<int> ID_Group { get; set; }
        public System.DateTime Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public string Target { get; set; }
        public int ID_Division { get; set; }
        public int ID_Employe_Division { get; set; }
    
        public virtual Division Division { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual Visitors Visitors { get; set; }
    }
}
