//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeeperPRO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_Authorization
    {
        public int ID_Auth { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<int> ID_User { get; set; }
    
        public virtual Visitors Visitors { get; set; }
    }
}
