//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeeperPRO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ATaran_KII_DemExEntities : DbContext
    {
        public ATaran_KII_DemExEntities()
            : base("name=ATaran_KII_DemExEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Applications> Applications { get; set; }
        public virtual DbSet<Data_Authorization> Data_Authorization { get; set; }
        public virtual DbSet<Departament> Departament { get; set; }
        public virtual DbSet<Division> Division { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Visitors> Visitors { get; set; }
        public virtual DbSet<Visits> Visits { get; set; }
        public virtual DbSet<BlackList> BlackList { get; set; }
    }
}
