//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeeperPRO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int ID { get; set; }
        public string FIO { get; set; }
        public Nullable<int> ID_Gender { get; set; }
        public Nullable<int> ID_Post { get; set; }
        public Nullable<int> ID_TypeUser { get; set; }
        public string SecretWord { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual Genders Genders { get; set; }
        public virtual Posts Posts { get; set; }
        public virtual TypeUser TypeUser { get; set; }
    }
}
