//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeeperPRO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visits
    {
        public int ID_Visit { get; set; }
        public int ID_Visitor { get; set; }
        public System.DateTime Date_Visit { get; set; }
        public int ID_Employee { get; set; }
        public Nullable<int> ID_Group { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual Visitors Visitors { get; set; }
    }
}
